// LeetCode 1841 - League Statistics
// https://leetcode.com/problems/league-statistics/

const char* QUERY =
    "\n"
    "WITH HomeStats AS (\n"
    "    SELECT\n"
    "        home_team_id AS team_id,\n"
    "        1 AS matches_played,\n"
    "        CASE\n"
    "            WHEN home_team_goals > away_team_goals THEN 3\n"
    "            WHEN home_team_goals = away_team_goals THEN 1\n"
    "            ELSE 0\n"
    "        END AS points,\n"
    "        home_team_goals AS goal_for,\n"
    "        away_team_goals AS goal_against\n"
    "    FROM Matches\n"
    "),\n"
    "AwayStats AS (\n"
    "    SELECT\n"
    "        away_team_id AS team_id,\n"
    "        1 AS matches_played,\n"
    "        CASE\n"
    "            WHEN away_team_goals > home_team_goals THEN 3\n"
    "            WHEN away_team_goals = home_team_goals THEN 1\n"
    "            ELSE 0\n"
    "        END AS points,\n"
    "        away_team_goals AS goal_for,\n"
    "        home_team_goals AS goal_against\n"
    "    FROM Matches\n"
    "),\n"
    "Combined AS (\n"
    "    SELECT * FROM HomeStats\n"
    "    UNION ALL\n"
    "    SELECT * FROM AwayStats\n"
    "),\n"
    "Aggregated AS (\n"
    "    SELECT\n"
    "        team_id,\n"
    "        SUM(matches_played) AS matches_played,\n"
    "        SUM(points) AS points,\n"
    "        SUM(goal_for) AS goal_for,\n"
    "        SUM(goal_against) AS goal_against\n"
    "    FROM Combined\n"
    "    GROUP BY team_id\n"
    ")\n"
    "SELECT\n"
    "    t.team_name,\n"
    "    a.matches_played,\n"
    "    a.points,\n"
    "    a.goal_for,\n"
    "    a.goal_against,\n"
    "    a.goal_for - a.goal_against AS goal_diff\n"
    "FROM Teams t\n"
    "JOIN Aggregated a ON t.team_id = a.team_id\n"
    "ORDER BY a.points DESC, goal_diff DESC, t.team_name ASC\n";
