
$files = [
    "/workspace/3062_winner_of_the_linked_list_game/solution.php",
    "/workspace/3063_linked_list_frequency/solution.php",
    "/workspace/3064_guess_the_number_using_bitwise_questions_i/solution.php",
    "/workspace/3065_minimum_operations_to_exceed_threshold_value_i/solution.php",
    "/workspace/3066_minimum_operations_to_exceed_threshold_value_ii/solution.php",
    "/workspace/3067_count_pairs_of_connectable_servers_in_a_weighted_tree_network/solution.php",
    "/workspace/3068_find_the_maximum_sum_of_node_values/solution.php",
    "/workspace/3069_distribute_elements_into_two_arrays_i/solution.php",
    "/workspace/3070_count_submatrices_with_top_left_element_and_sum_less_than_k/solution.php",
    "/workspace/3071_minimum_operations_to_write_the_letter_y_on_a_grid/solution.php",
    "/workspace/3072_distribute_elements_into_two_arrays_ii/solution.php",
    "/workspace/3073_maximum_increasing_triplet_value/solution.php",
    "/workspace/3074_apple_redistribution_into_boxes/solution.php",
    "/workspace/3075_maximize_happiness_of_selected_children/solution.php",
    "/workspace/3076_shortest_uncommon_substring_in_an_array/solution.php",
    "/workspace/3077_maximum_strength_of_k_disjoint_subarrays/solution.php",
    "/workspace/3078_match_alphanumerical_pattern_in_matrix_i/solution.php",
    "/workspace/3079_find_the_sum_of_encrypted_integers/solution.php",
    "/workspace/3080_mark_elements_on_array_by_performing_queries/solution.php",
    "/workspace/3081_replace_question_marks_in_string_to_minimize_its_value/solution.php",
    "/workspace/3082_find_the_sum_of_the_power_of_all_subsequences/solution.php",
    "/workspace/3083_existence_of_a_substring_in_a_string_and_its_reverse/solution.php",
    "/workspace/3084_count_substrings_starting_and_ending_with_given_character/solution.php",
    "/workspace/3085_minimum_deletions_to_make_string_k_special/solution.php",
    "/workspace/3086_minimum_moves_to_pick_k_ones/solution.php",
    "/workspace/3088_make_string_anti_palindrome/solution.php",
    "/workspace/3090_maximum_length_substring_with_two_occurrences/solution.php",
    "/workspace/3091_apply_operations_to_make_sum_of_array_greater_than_or_equal_to_k/solution.php",
    "/workspace/3092_most_frequent_ids/solution.php",
    "/workspace/3093_longest_common_suffix_queries/solution.php",
    "/workspace/3094_guess_the_number_using_bitwise_questions_ii/solution.php",
    "/workspace/3095_shortest_subarray_with_or_at_least_k_i/solution.php",
    "/workspace/3096_minimum_levels_to_gain_more_points/solution.php",
    "/workspace/3097_shortest_subarray_with_or_at_least_k_ii/solution.php",
    "/workspace/3098_find_the_sum_of_subsequence_powers/solution.php",
    "/workspace/3099_harshad_number/solution.php",
    "/workspace/3100_water_bottles_ii/solution.php",
    "/workspace/3101_count_alternating_subarrays/solution.php",
    "/workspace/3102_minimize_manhattan_distances/solution.php",
    "/workspace/3104_find_longest_self_contained_substring/solution.php",
    "/workspace/3105_longest_strictly_increasing_or_strictly_decreasing_subarray/solution.php",
    "/workspace/3106_lexicographically_smallest_string_after_operations_with_constraint/solution.php",
    "/workspace/3107_minimum_operations_to_make_median_of_array_equal_to_k/solution.php",
    "/workspace/3108_minimum_cost_walk_in_weighted_graph/solution.php",
    "/workspace/3109_find_the_index_of_permutation/solution.php",
    "/workspace/3110_score_of_a_string/solution.php",
    "/workspace/3111_minimum_rectangles_to_cover_points/solution.php",
    "/workspace/3112_minimum_time_to_visit_disappearing_nodes/solution.php",
    "/workspace/3113_find_the_number_of_subarrays_where_boundary_elements_are_maximum/solution.php",
    "/workspace/3114_latest_time_you_can_obtain_after_replacing_characters/solution.php",
    "/workspace/3115_maximum_prime_difference/solution.php",
    "/workspace/3116_kth_smallest_amount_with_single_denomination_combination/solution.php",
    "/workspace/3117_minimum_sum_of_values_by_dividing_array/solution.php",
    "/workspace/3119_maximum_number_of_potholes_that_can_be_fixed/solution.php",
    "/workspace/3120_count_the_number_of_special_characters_i/solution.php",
    "/workspace/3121_count_the_number_of_special_characters_ii/solution.php",
    "/workspace/3122_minimum_number_of_operations_to_satisfy_conditions/solution.php",
    "/workspace/3123_find_edges_in_shortest_paths/solution.php",
    "/workspace/3125_maximum_number_that_makes_result_of_bitwise_and_zero/solution.php",
    "/workspace/3127_make_a_square_with_the_same_color/solution.php",
    "/workspace/3128_right_triangles/solution.php",
    "/workspace/3129_find_all_possible_stable_binary_arrays_i/solution.php",
    "/workspace/3130_find_all_possible_stable_binary_arrays_ii/solution.php",
    "/workspace/3131_find_the_integer_added_to_array_i/solution.php",
    "/workspace/3132_find_the_integer_added_to_array_ii/solution.php",
    "/workspace/3133_minimum_array_end/solution.php",
    "/workspace/3134_find_the_median_of_the_uniqueness_array/solution.php",
    "/workspace/3135_equalize_strings_by_adding_or_removing_characters_at_ends/solution.php",
    "/workspace/3136_valid_word/solution.php",
    "/workspace/3137_minimum_number_of_operations_to_make_word_k_periodic/solution.php",
    "/workspace/3138_minimum_length_of_anagram_concatenation/solution.php",
    "/workspace/3139_minimum_cost_to_equalize_array/solution.php",
    "/workspace/3141_maximum_hamming_distances/solution.php",
    "/workspace/3142_check_if_grid_satisfies_conditions/solution.php",
    "/workspace/3143_maximum_points_inside_the_square/solution.php",
    "/workspace/3144_minimum_substring_partition_of_equal_character_frequency/solution.php",
    "/workspace/3145_find_products_of_elements_of_big_array/solution.php",
    "/workspace/3146_permutation_difference_between_two_strings/solution.php",
    "/workspace/3147_taking_maximum_energy_from_the_mystic_dungeon/solution.php",
    "/workspace/3148_maximum_difference_score_in_a_grid/solution.php",
    "/workspace/3149_find_the_minimum_cost_array_permutation/solution.php",
    "/workspace/3151_special_array_i/solution.php",
    "/workspace/3152_special_array_ii/solution.php",
    "/workspace/3153_sum_of_digit_differences_of_all_pairs/solution.php",
    "/workspace/3154_find_number_of_ways_to_reach_the_k_th_stair/solution.php",
    "/workspace/3155_maximum_number_of_upgradable_servers/solution.php",
    "/workspace/3157_find_the_level_of_tree_with_minimum_sum/solution.php",
    "/workspace/3158_find_the_xor_of_numbers_which_appear_twice/solution.php",
    "/workspace/3159_find_occurrences_of_an_element_in_an_array/solution.php",
    "/workspace/3160_find_the_number_of_distinct_colors_among_the_balls/solution.php",
    "/workspace/3161_block_placement_queries/solution.php",
    "/workspace/3162_find_the_number_of_good_pairs_i/solution.php",
    "/workspace/3163_string_compression_iii/solution.php",
    "/workspace/3164_find_the_number_of_good_pairs_ii/solution.php",
    "/workspace/3165_maximum_sum_of_subsequence_with_non_adjacent_elements/solution.php",
    "/workspace/3167_better_compression_of_string/solution.php",
    "/workspace/3168_minimum_number_of_chairs_in_a_waiting_room/solution.php",
    "/workspace/3169_count_days_without_meetings/solution.php",
    "/workspace/3170_lexicographically_minimum_string_after_removing_stars/solution.php",
    "/workspace/3171_find_subarray_with_bitwise_or_closest_to_k/solution.php"
];
$ok = 0; $fail = 0;
foreach ($files as $f) {
    $out = [];
    $code = 0;
    exec('php -l ' . escapeshellarg($f) . ' 2>&1', $out, $code);
    if ($code !== 0) {
        $fail++;
        echo "FAIL $f\n" . implode("\n", $out) . "\n";
    } else {
        $ok++;
    }
}
echo "ok=$ok fail=$fail\n";
