from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def standard(method: str, params: list[str], cases: list[dict], types: dict | None = None) -> dict:
    config = {
        "class": "Solution",
        "method": method,
        "paramOrder": params,
        "types": types,
        "description": "Generated by scripts/_batch_1701_1750.py.",
    }
    return {"config": config, "cases": {"cases": cases}}


def sql_cases() -> dict:
    return {
        "config": {
            "class": "Solution",
            "method": "query",
            "description": "Generated by scripts/_batch_1701_1750.py.",
            "kind": "sql",
            "runnable": False,
        },
        "cases": {"cases": [{"kind": "sql", "expected": []}]},
    }


SOLUTIONS: dict[int, str] = {
    1701: '''from typing import List


class Solution:
    def averageWaitingTime(self, customers: List[List[int]]) -> float:
        current = 0
        total = 0
        for arrival, cook in customers:
            current = max(current, arrival) + cook
            total += current - arrival
        return total / len(customers)
''',
    1702: '''class Solution:
    def maximumBinaryString(self, binary: str) -> str:
        zeros = binary.count("0")
        if zeros <= 1:
            return binary
        first = binary.find("0")
        return "1" * (first + zeros - 1) + "0" + "1" * (len(binary) - first - zeros)
''',
    1703: '''from typing import List


class Solution:
    def minMoves(self, nums: List[int], k: int) -> int:
        ones = [i for i, v in enumerate(nums) if v == 1]
        adjusted = [pos - i for i, pos in enumerate(ones)]
        prefix = [0]
        for value in adjusted:
            prefix.append(prefix[-1] + value)
        best = 10 ** 30
        for left in range(len(ones) - k + 1):
            right = left + k
            mid = left + k // 2
            median = adjusted[mid]
            cost = median * (mid - left) - (prefix[mid] - prefix[left])
            cost += (prefix[right] - prefix[mid + 1]) - median * (right - mid - 1)
            best = min(best, cost)
        return best
''',
    1704: '''class Solution:
    def halvesAreAlike(self, s: str) -> bool:
        vowels = set("aeiouAEIOU")
        mid = len(s) // 2
        return sum(ch in vowels for ch in s[:mid]) == sum(ch in vowels for ch in s[mid:])
''',
    1705: '''from heapq import heappop, heappush
from typing import List


class Solution:
    def eatenApples(self, apples: List[int], days: List[int]) -> int:
        heap = []
        day = eaten = 0
        n = len(apples)
        while day < n or heap:
            if day < n and apples[day]:
                heappush(heap, (day + days[day], apples[day]))
            while heap and heap[0][0] <= day:
                heappop(heap)
            if heap:
                expire, count = heappop(heap)
                eaten += 1
                if count > 1:
                    heappush(heap, (expire, count - 1))
            day += 1
        return eaten
''',
    1706: '''from typing import List


class Solution:
    def findBall(self, grid: List[List[int]]) -> List[int]:
        m, n = len(grid), len(grid[0])
        ans = []
        for start in range(n):
            col = start
            for row in range(m):
                nxt = col + grid[row][col]
                if nxt < 0 or nxt == n or grid[row][nxt] != grid[row][col]:
                    col = -1
                    break
                col = nxt
            ans.append(col)
        return ans
''',
    1707: '''from typing import List


class Trie:
    def __init__(self) -> None:
        self.child = [None, None]


class Solution:
    def maximizeXor(self, nums: List[int], queries: List[List[int]]) -> List[int]:
        nums.sort()
        indexed = sorted((m, x, i) for i, (x, m) in enumerate(queries))
        ans = [-1] * len(queries)
        root = Trie()
        added = 0

        def insert(num: int) -> None:
            node = root
            for bit in range(31, -1, -1):
                b = (num >> bit) & 1
                if node.child[b] is None:
                    node.child[b] = Trie()
                node = node.child[b]

        for limit, x, qi in indexed:
            while added < len(nums) and nums[added] <= limit:
                insert(nums[added])
                added += 1
            if added == 0:
                continue
            node = root
            value = 0
            for bit in range(31, -1, -1):
                b = (x >> bit) & 1
                want = b ^ 1
                if node.child[want] is not None:
                    value |= 1 << bit
                    node = node.child[want]
                else:
                    node = node.child[b]
            ans[qi] = value
        return ans
''',
    1708: '''from typing import List


class Solution:
    def largestSubarray(self, nums: List[int], k: int) -> List[int]:
        start = max(range(len(nums) - k + 1), key=nums.__getitem__)
        return nums[start:start + k]
''',
    1709: '''QUERY = """
SELECT user_id, MAX(DATEDIFF(next_visit, visit_date)) AS biggest_window
FROM (
    SELECT
        user_id,
        visit_date,
        LEAD(visit_date, 1, '2021-1-1') OVER (
            PARTITION BY user_id
            ORDER BY visit_date
        ) AS next_visit
    FROM UserVisits
) AS visits
GROUP BY user_id
ORDER BY user_id;
"""
''',
    1710: '''from typing import List


class Solution:
    def maximumUnits(self, boxTypes: List[List[int]], truckSize: int) -> int:
        total = 0
        for count, units in sorted(boxTypes, key=lambda item: -item[1]):
            take = min(count, truckSize)
            total += take * units
            truckSize -= take
            if truckSize == 0:
                break
        return total
''',
    1711: '''from collections import Counter
from typing import List


class Solution:
    def countPairs(self, deliciousness: List[int]) -> int:
        mod = 10 ** 9 + 7
        seen = Counter()
        ans = 0
        for value in deliciousness:
            for power in range(22):
                ans += seen[(1 << power) - value]
            seen[value] += 1
        return ans % mod
''',
    1712: '''from bisect import bisect_left, bisect_right
from typing import List


class Solution:
    def waysToSplit(self, nums: List[int]) -> int:
        mod = 10 ** 9 + 7
        prefix = []
        total = 0
        for value in nums:
            total += value
            prefix.append(total)
        ans = 0
        n = len(nums)
        for i in range(n - 2):
            left = prefix[i]
            lo = bisect_left(prefix, 2 * left, i + 1, n - 1)
            hi = bisect_right(prefix, (total + left) // 2, lo, n - 1)
            ans = (ans + hi - lo) % mod
        return ans
''',
    1713: '''from bisect import bisect_left
from typing import List


class Solution:
    def minOperations(self, target: List[int], arr: List[int]) -> int:
        pos = {value: i for i, value in enumerate(target)}
        lis = []
        for value in arr:
            if value not in pos:
                continue
            idx = pos[value]
            place = bisect_left(lis, idx)
            if place == len(lis):
                lis.append(idx)
            else:
                lis[place] = idx
        return len(target) - len(lis)
''',
    1714: '''from math import isqrt
from typing import List


class Solution:
    def solve(self, nums: List[int], queries: List[List[int]]) -> List[int]:
        mod = 10 ** 9 + 7
        n = len(nums)
        block = isqrt(n) + 1
        dp = [[0] * n for _ in range(block)]
        for step in range(1, block):
            for i in range(n - 1, -1, -1):
                dp[step][i] = (nums[i] + (dp[step][i + step] if i + step < n else 0)) % mod
        ans = []
        for start, step in queries:
            if step < block:
                ans.append(dp[step][start])
            else:
                total = 0
                for i in range(start, n, step):
                    total += nums[i]
                ans.append(total % mod)
        return ans
''',
    1715: '''QUERY = """
SELECT SUM(apple_count) AS apple_count, SUM(orange_count) AS orange_count
FROM (
    SELECT apple_count, orange_count FROM Boxes
    UNION ALL
    SELECT apple_count, orange_count
    FROM Chests
    WHERE chest_id IN (SELECT chest_id FROM Boxes WHERE chest_id IS NOT NULL)
) AS counts;
"""
''',
    1716: '''class Solution:
    def totalMoney(self, n: int) -> int:
        weeks, days = divmod(n, 7)
        return weeks * 28 + 7 * weeks * (weeks - 1) // 2 + days * (weeks + 1) + days * (days - 1) // 2
''',
    1717: '''class Solution:
    def maximumGain(self, s: str, x: int, y: int) -> int:
        def remove(text: str, pair: str, score: int) -> tuple[str, int]:
            stack = []
            gained = 0
            for ch in text:
                if stack and stack[-1] == pair[0] and ch == pair[1]:
                    stack.pop()
                    gained += score
                else:
                    stack.append(ch)
            return "".join(stack), gained

        if x >= y:
            rest, first = remove(s, "ab", x)
            _, second = remove(rest, "ba", y)
        else:
            rest, first = remove(s, "ba", y)
            _, second = remove(rest, "ab", x)
        return first + second
''',
    1718: '''from typing import List


class Solution:
    def constructDistancedSequence(self, n: int) -> List[int]:
        ans = [0] * (2 * n - 1)
        used = [False] * (n + 1)

        def backtrack(i: int) -> bool:
            while i < len(ans) and ans[i]:
                i += 1
            if i == len(ans):
                return True
            for value in range(n, 0, -1):
                if used[value]:
                    continue
                if value == 1:
                    ans[i] = 1
                    used[1] = True
                    if backtrack(i + 1):
                        return True
                    used[1] = False
                    ans[i] = 0
                else:
                    j = i + value
                    if j < len(ans) and ans[j] == 0:
                        ans[i] = ans[j] = value
                        used[value] = True
                        if backtrack(i + 1):
                            return True
                        used[value] = False
                        ans[i] = ans[j] = 0
            return False

        backtrack(0)
        return ans
''',
    1719: '''from collections import defaultdict
from typing import List


class Solution:
    def checkWays(self, pairs: List[List[int]]) -> int:
        graph = defaultdict(set)
        for a, b in pairs:
            graph[a].add(b)
            graph[b].add(a)
        nodes = list(graph)
        n = len(nodes)
        root = next((node for node in nodes if len(graph[node]) == n - 1), None)
        if root is None:
            return 0
        ans = 1
        for node in nodes:
            if node == root:
                continue
            parent = None
            parent_degree = n + 1
            for nei in graph[node]:
                if len(graph[nei]) >= len(graph[node]) and len(graph[nei]) < parent_degree:
                    parent = nei
                    parent_degree = len(graph[nei])
            if parent is None:
                return 0
            for nei in graph[node]:
                if nei != parent and nei not in graph[parent]:
                    return 0
            if len(graph[parent]) == len(graph[node]):
                ans = 2
        return ans
''',
    1720: '''from typing import List


class Solution:
    def decode(self, encoded: List[int], first: int) -> List[int]:
        ans = [first]
        for value in encoded:
            ans.append(ans[-1] ^ value)
        return ans
''',
    1721: '''from typing import Optional


class ListNode:
    def __init__(self, val: int = 0, next: Optional["ListNode"] = None):
        self.val = val
        self.next = next


class Solution:
    def swapNodes(self, head: Optional[ListNode], k: int) -> Optional[ListNode]:
        first = head
        for _ in range(k - 1):
            first = first.next
        fast = first
        second = head
        while fast.next:
            fast = fast.next
            second = second.next
        first.val, second.val = second.val, first.val
        return head
''',
    1722: '''from collections import Counter, defaultdict
from typing import List


class DSU:
    def __init__(self, n: int) -> None:
        self.parent = list(range(n))

    def find(self, x: int) -> int:
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a: int, b: int) -> None:
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.parent[rb] = ra


class Solution:
    def minimumHammingDistance(self, source: List[int], target: List[int], allowedSwaps: List[List[int]]) -> int:
        dsu = DSU(len(source))
        for a, b in allowedSwaps:
            dsu.union(a, b)
        groups = defaultdict(Counter)
        for i, value in enumerate(source):
            groups[dsu.find(i)][value] += 1
        ans = 0
        for i, value in enumerate(target):
            group = groups[dsu.find(i)]
            if group[value]:
                group[value] -= 1
            else:
                ans += 1
        return ans
''',
    1723: '''from typing import List


class Solution:
    def minimumTimeRequired(self, jobs: List[int], k: int) -> int:
        jobs.sort(reverse=True)
        loads = [0] * k
        best = sum(jobs)

        def backtrack(i: int) -> None:
            nonlocal best
            if i == len(jobs):
                best = min(best, max(loads))
                return
            seen = set()
            for worker in range(k):
                if loads[worker] in seen:
                    continue
                if loads[worker] + jobs[i] >= best:
                    continue
                seen.add(loads[worker])
                loads[worker] += jobs[i]
                backtrack(i + 1)
                loads[worker] -= jobs[i]
                if loads[worker] == 0:
                    break

        backtrack(0)
        return best
''',
    1724: '''from bisect import bisect_left
from typing import List


class DSU:
    def __init__(self, n: int) -> None:
        self.parent = list(range(n))
        self.size = [1] * n

    def find(self, x: int) -> int:
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a: int, b: int) -> None:
        ra, rb = self.find(a), self.find(b)
        if ra == rb:
            return
        if self.size[ra] < self.size[rb]:
            ra, rb = rb, ra
        self.parent[rb] = ra
        self.size[ra] += self.size[rb]


class DistanceLimitedPathsExist:
    def __init__(self, n: int, edgeList: List[List[int]]):
        self.edges = sorted((w, u, v) for u, v, w in edgeList)
        self.weights = []
        self.versions = []
        dsu = DSU(n)
        i = 0
        while i < len(self.edges):
            weight = self.edges[i][0]
            while i < len(self.edges) and self.edges[i][0] == weight:
                _, u, v = self.edges[i]
                dsu.union(u, v)
                i += 1
            self.weights.append(weight)
            self.versions.append(tuple(dsu.parent))

    def query(self, p: int, q: int, limit: int) -> bool:
        idx = bisect_left(self.weights, limit) - 1
        if idx < 0:
            return p == q
        parent = self.versions[idx]

        def find(x: int) -> int:
            while parent[x] != x:
                x = parent[x]
            return x

        return find(p) == find(q)
''',
    1725: '''from typing import List


class Solution:
    def countGoodRectangles(self, rectangles: List[List[int]]) -> int:
        sides = [min(a, b) for a, b in rectangles]
        best = max(sides)
        return sides.count(best)
''',
    1726: '''from collections import Counter
from typing import List


class Solution:
    def tupleSameProduct(self, nums: List[int]) -> int:
        counts = Counter()
        for i in range(len(nums)):
            for j in range(i + 1, len(nums)):
                counts[nums[i] * nums[j]] += 1
        return sum(count * (count - 1) * 4 for count in counts.values())
''',
    1727: '''from typing import List


class Solution:
    def largestSubmatrix(self, matrix: List[List[int]]) -> int:
        m, n = len(matrix), len(matrix[0])
        heights = [0] * n
        best = 0
        for r in range(m):
            for c in range(n):
                heights[c] = heights[c] + 1 if matrix[r][c] else 0
            for width, height in enumerate(sorted(heights, reverse=True), 1):
                best = max(best, width * height)
        return best
''',
    1728: '''from functools import lru_cache
from typing import List


class Solution:
    def canMouseWin(self, grid: List[str], catJump: int, mouseJump: int) -> bool:
        rows, cols = len(grid), len(grid[0])
        total_open = 0
        for r in range(rows):
            for c in range(cols):
                if grid[r][c] != "#":
                    total_open += 1
                if grid[r][c] == "M":
                    mouse = r * cols + c
                elif grid[r][c] == "C":
                    cat = r * cols + c
                elif grid[r][c] == "F":
                    food = r * cols + c

        def moves(pos: int, jump: int) -> list[int]:
            r, c = divmod(pos, cols)
            out = [pos]
            for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                for step in range(1, jump + 1):
                    nr, nc = r + dr * step, c + dc * step
                    if not (0 <= nr < rows and 0 <= nc < cols) or grid[nr][nc] == "#":
                        break
                    out.append(nr * cols + nc)
            return out

        mouse_moves = {}
        cat_moves = {}
        for r in range(rows):
            for c in range(cols):
                if grid[r][c] != "#":
                    pos = r * cols + c
                    mouse_moves[pos] = moves(pos, mouseJump)
                    cat_moves[pos] = moves(pos, catJump)

        @lru_cache(None)
        def win(m: int, c: int, turn: int) -> bool:
            if turn >= 2 * total_open:
                return False
            if m == food:
                return True
            if c == food or c == m:
                return False
            if turn % 2 == 0:
                return any(win(nm, c, turn + 1) for nm in mouse_moves[m])
            return all(win(m, nc, turn + 1) for nc in cat_moves[c])

        return win(mouse, cat, 0)
''',
    1729: '''QUERY = """
SELECT user_id, COUNT(follower_id) AS followers_count
FROM Followers
GROUP BY user_id
ORDER BY user_id;
"""
''',
    1730: '''from collections import deque
from typing import List


class Solution:
    def getFood(self, grid: List[List[str]]) -> int:
        rows, cols = len(grid), len(grid[0])
        queue = deque()
        seen = set()
        for r in range(rows):
            for c in range(cols):
                if grid[r][c] == "*":
                    queue.append((r, c, 0))
                    seen.add((r, c))
        while queue:
            r, c, d = queue.popleft()
            if grid[r][c] == "#":
                return d
            for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nr, nc = r + dr, c + dc
                if 0 <= nr < rows and 0 <= nc < cols and (nr, nc) not in seen and grid[nr][nc] != "X":
                    seen.add((nr, nc))
                    queue.append((nr, nc, d + 1))
        return -1
''',
    1731: '''QUERY = """
SELECT
    e.employee_id,
    e.name,
    COUNT(r.employee_id) AS reports_count,
    ROUND(AVG(r.age)) AS average_age
FROM Employees e
JOIN Employees r ON e.employee_id = r.reports_to
GROUP BY e.employee_id, e.name
ORDER BY e.employee_id;
"""
''',
    1732: '''from typing import List


class Solution:
    def largestAltitude(self, gain: List[int]) -> int:
        altitude = best = 0
        for change in gain:
            altitude += change
            best = max(best, altitude)
        return best
''',
    1733: '''from typing import List


class Solution:
    def minimumTeachings(self, n: int, languages: List[List[int]], friendships: List[List[int]]) -> int:
        known = [set(items) for items in languages]
        need = set()
        for u, v in friendships:
            if known[u - 1].isdisjoint(known[v - 1]):
                need.add(u - 1)
                need.add(v - 1)
        if not need:
            return 0
        return min(sum(lang not in known[user] for user in need) for lang in range(1, n + 1))
''',
    1734: '''from typing import List


class Solution:
    def decode(self, encoded: List[int]) -> List[int]:
        n = len(encoded) + 1
        total = 0
        for value in range(1, n + 1):
            total ^= value
        odd = 0
        for i in range(1, len(encoded), 2):
            odd ^= encoded[i]
        first = total ^ odd
        ans = [first]
        for value in encoded:
            ans.append(ans[-1] ^ value)
        return ans
''',
    1735: '''from math import comb, isqrt
from typing import List


class Solution:
    def waysToFillArray(self, queries: List[List[int]]) -> List[int]:
        mod = 10 ** 9 + 7
        ans = []
        for n, k in queries:
            ways = 1
            d = 2
            value = k
            while d * d <= value:
                if value % d == 0:
                    exp = 0
                    while value % d == 0:
                        value //= d
                        exp += 1
                    ways = ways * comb(n + exp - 1, exp) % mod
                d += 1 if d == 2 else 2
            if value > 1:
                ways = ways * n % mod
            ans.append(ways)
        return ans
''',
    1736: '''class Solution:
    def maximumTime(self, time: str) -> str:
        chars = list(time)
        if chars[0] == "?":
            chars[0] = "2" if chars[1] in "0123?" else "1"
        if chars[1] == "?":
            chars[1] = "3" if chars[0] == "2" else "9"
        if chars[3] == "?":
            chars[3] = "5"
        if chars[4] == "?":
            chars[4] = "9"
        return "".join(chars)
''',
    1737: '''from collections import Counter


class Solution:
    def minCharacters(self, a: str, b: str) -> int:
        ca, cb = Counter(a), Counter(b)
        n, m = len(a), len(b)
        ans = n + m - max(max(ca.values()), max(cb.values()))
        pre_a = pre_b = 0
        for code in range(25):
            ch = chr(ord("a") + code)
            pre_a += ca[ch]
            pre_b += cb[ch]
            ans = min(ans, n - pre_a + pre_b, m - pre_b + pre_a)
        return ans
''',
    1738: '''from heapq import nlargest
from typing import List


class Solution:
    def kthLargestValue(self, matrix: List[List[int]], k: int) -> int:
        rows, cols = len(matrix), len(matrix[0])
        pref = [[0] * (cols + 1) for _ in range(rows + 1)]
        values = []
        for r in range(1, rows + 1):
            for c in range(1, cols + 1):
                pref[r][c] = pref[r - 1][c] ^ pref[r][c - 1] ^ pref[r - 1][c - 1] ^ matrix[r - 1][c - 1]
                values.append(pref[r][c])
        return nlargest(k, values)[-1]
''',
    1739: '''class Solution:
    def minimumBoxes(self, n: int) -> int:
        height = 0
        used = 0
        base = 0
        while used + (height + 1) * (height + 2) // 2 <= n:
            height += 1
            layer = height * (height + 1) // 2
            used += layer
            base += height
        extra = 0
        while used < n:
            extra += 1
            used += extra
        return base + extra
''',
    1740: '''from collections import deque
from typing import Optional


class TreeNode:
    def __init__(self, val: int = 0, left: Optional["TreeNode"] = None, right: Optional["TreeNode"] = None):
        self.val = val
        self.left = left
        self.right = right


class Solution:
    def findDistance(self, root: Optional[TreeNode], p: int, q: int) -> int:
        graph = {}

        def dfs(node: Optional[TreeNode], parent: Optional[TreeNode]) -> None:
            if not node:
                return
            graph.setdefault(node.val, [])
            if parent:
                graph[node.val].append(parent.val)
                graph[parent.val].append(node.val)
            dfs(node.left, node)
            dfs(node.right, node)

        dfs(root, None)
        queue = deque([(p, 0)])
        seen = {p}
        while queue:
            node, dist = queue.popleft()
            if node == q:
                return dist
            for nei in graph[node]:
                if nei not in seen:
                    seen.add(nei)
                    queue.append((nei, dist + 1))
        return -1
''',
    1741: '''QUERY = """
SELECT event_day AS day, emp_id, SUM(out_time - in_time) AS total_time
FROM Employees
GROUP BY event_day, emp_id;
"""
''',
    1742: '''class Solution:
    def countBalls(self, lowLimit: int, highLimit: int) -> int:
        counts = {}
        for value in range(lowLimit, highLimit + 1):
            box = sum(map(int, str(value)))
            counts[box] = counts.get(box, 0) + 1
        return max(counts.values())
''',
    1743: '''from collections import defaultdict
from typing import List


class Solution:
    def restoreArray(self, adjacentPairs: List[List[int]]) -> List[int]:
        graph = defaultdict(list)
        for a, b in adjacentPairs:
            graph[a].append(b)
            graph[b].append(a)
        start = next(node for node, neighbors in graph.items() if len(neighbors) == 1)
        ans = [start]
        prev = None
        while len(ans) < len(graph):
            cur = ans[-1]
            nxt = graph[cur][0] if graph[cur][0] != prev else graph[cur][1]
            ans.append(nxt)
            prev = cur
        return ans
''',
    1744: '''from typing import List


class Solution:
    def canEat(self, candiesCount: List[int], queries: List[List[int]]) -> List[bool]:
        prefix = [0]
        for count in candiesCount:
            prefix.append(prefix[-1] + count)
        ans = []
        for candy_type, day, cap in queries:
            min_eaten = day + 1
            max_eaten = (day + 1) * cap
            ans.append(max_eaten > prefix[candy_type] and min_eaten <= prefix[candy_type + 1])
        return ans
''',
    1745: '''class Solution:
    def checkPartitioning(self, s: str) -> bool:
        n = len(s)
        pal = [[False] * n for _ in range(n)]
        for i in range(n - 1, -1, -1):
            for j in range(i, n):
                pal[i][j] = s[i] == s[j] and (j - i < 2 or pal[i + 1][j - 1])
        for i in range(n - 2):
            for j in range(i + 1, n - 1):
                if pal[0][i] and pal[i + 1][j] and pal[j + 1][n - 1]:
                    return True
        return False
''',
    1746: '''from typing import List


class Solution:
    def maxSumAfterOperation(self, nums: List[int]) -> int:
        no_square = 0
        one_square = 0
        best = -10 ** 18
        for value in nums:
            one_square = max(one_square + value, no_square + value * value, value * value)
            no_square = max(no_square + value, value)
            best = max(best, one_square)
        return best
''',
    1747: '''QUERY = """
SELECT DISTINCT l1.account_id
FROM LogInfo l1
JOIN LogInfo l2
  ON l1.account_id = l2.account_id
 AND l1.ip_address <> l2.ip_address
 AND l1.login <= l2.logout
 AND l2.login <= l1.logout;
"""
''',
    1748: '''from collections import Counter
from typing import List


class Solution:
    def sumOfUnique(self, nums: List[int]) -> int:
        counts = Counter(nums)
        return sum(value for value, count in counts.items() if count == 1)
''',
    1749: '''from typing import List


class Solution:
    def maxAbsoluteSum(self, nums: List[int]) -> int:
        prefix = 0
        low = high = 0
        for value in nums:
            prefix += value
            low = min(low, prefix)
            high = max(high, prefix)
        return high - low
''',
    1750: '''class Solution:
    def minimumLength(self, s: str) -> int:
        left, right = 0, len(s) - 1
        while left < right and s[left] == s[right]:
            ch = s[left]
            while left <= right and s[left] == ch:
                left += 1
            while left <= right and s[right] == ch:
                right -= 1
        return right - left + 1
''',
}


META: dict[int, tuple[str, str, dict]] = {
    1701: ("1701_average_waiting_time", "Average waiting time by simulating the chef's next free time.", standard("averageWaitingTime", ["customers"], [{"args": {"customers": [[1, 2], [2, 5], [4, 3]]}, "expected": 5.0}, {"args": {"customers": [[5, 2], [5, 4], [10, 3], [20, 1]]}, "expected": 3.25}])),
    1702: ("1702_maximum_binary_string_after_change", "All zeros collapse into one zero at the forced position after the first zero.", standard("maximumBinaryString", ["binary"], [{"args": {"binary": "000110"}, "expected": "111011"}, {"args": {"binary": "01"}, "expected": "01"}])),
    1703: ("1703_minimum_adjacent_swaps_for_k_consecutive_ones", "Use one positions normalized by their order, then minimize each k-window around its median.", standard("minMoves", ["nums", "k"], [{"args": {"nums": [1, 0, 0, 1, 0, 1], "k": 2}, "expected": 1}, {"args": {"nums": [1, 0, 0, 0, 0, 0, 1, 1], "k": 3}, "expected": 5}, {"args": {"nums": [1, 1, 0, 1], "k": 2}, "expected": 0}])),
    1704: ("1704_determine_if_string_halves_are_alike", "Count vowels independently in both halves.", standard("halvesAreAlike", ["s"], [{"args": {"s": "book"}, "expected": True}, {"args": {"s": "textbook"}, "expected": False}])),
    1705: ("1705_maximum_number_of_eaten_apples", "Greedily eat the apple batch with the earliest expiration day.", standard("eatenApples", ["apples", "days"], [{"args": {"apples": [1, 2, 3, 5, 2], "days": [3, 2, 1, 4, 2]}, "expected": 7}, {"args": {"apples": [3, 0, 0, 0, 0, 2], "days": [3, 0, 0, 0, 0, 2]}, "expected": 5}])),
    1706: ("1706_where_will_the_ball_fall", "Simulate each ball and stop at walls or V-shaped traps.", standard("findBall", ["grid"], [{"args": {"grid": [[1, 1, 1, -1, -1], [1, 1, 1, -1, -1], [-1, -1, -1, 1, 1], [1, 1, 1, 1, -1], [-1, -1, -1, -1, -1]]}, "expected": [1, -1, -1, -1, -1]}, {"args": {"grid": [[-1]]}, "expected": [-1]}])),
    1707: ("1707_maximum_xor_with_an_element_from_array", "Sort queries by limit and insert eligible numbers into a bit trie.", standard("maximizeXor", ["nums", "queries"], [{"args": {"nums": [0, 1, 2, 3, 4], "queries": [[3, 1], [1, 3], [5, 6]]}, "expected": [3, 3, 7]}, {"args": {"nums": [5, 2, 4, 6, 6, 3], "queries": [[12, 4], [8, 1], [6, 3]]}, "expected": [15, -1, 5]}])),
    1708: ("1708_largest_subarray_length_k", "The lexicographically largest fixed-length slice starts at the largest valid first element.", standard("largestSubarray", ["nums", "k"], [{"args": {"nums": [1, 4, 5, 2, 3], "k": 3}, "expected": [5, 2, 3]}, {"args": {"nums": [1, 4, 5, 2, 3], "k": 4}, "expected": [4, 5, 2, 3]}])),
    1709: ("1709_biggest_window_between_visits", "Use LEAD with the sentinel date and aggregate each user's largest gap.", sql_cases()),
    1710: ("1710_maximum_units_on_a_truck", "Take boxes greedily in descending units per box.", standard("maximumUnits", ["boxTypes", "truckSize"], [{"args": {"boxTypes": [[1, 3], [2, 2], [3, 1]], "truckSize": 4}, "expected": 8}, {"args": {"boxTypes": [[5, 10], [2, 5], [4, 7], [3, 9]], "truckSize": 10}, "expected": 91}])),
    1711: ("1711_count_good_meals", "For every meal, count prior complements to each power of two.", standard("countPairs", ["deliciousness"], [{"args": {"deliciousness": [1, 3, 5, 7, 9]}, "expected": 4}, {"args": {"deliciousness": [1, 1, 1, 3, 3, 3, 7]}, "expected": 15}])),
    1712: ("1712_ways_to_split_array_into_three_subarrays", "Prefix sums make the valid middle interval searchable with binary search.", standard("waysToSplit", ["nums"], [{"args": {"nums": [1, 1, 1]}, "expected": 1}, {"args": {"nums": [1, 2, 2, 2, 5, 0]}, "expected": 3}, {"args": {"nums": [3, 2, 1]}, "expected": 0}])),
    1713: ("1713_minimum_operations_to_make_a_subsequence", "Map target values to indexes and keep the LIS of indexes seen in arr.", standard("minOperations", ["target", "arr"], [{"args": {"target": [5, 1, 3], "arr": [9, 4, 2, 3, 4]}, "expected": 2}, {"args": {"target": [6, 4, 8, 1, 3, 2], "arr": [4, 7, 6, 2, 3, 8, 6, 1]}, "expected": 3}])),
    1714: ("1714_sum_of_special_evenly_spaced_elements_in_array", "Precompute sums for small step sizes and scan directly for large steps.", standard("solve", ["nums", "queries"], [{"args": {"nums": [0, 1, 2, 3, 4, 5, 6, 7], "queries": [[0, 3], [5, 1], [4, 2]]}, "expected": [9, 18, 10]}, {"args": {"nums": [1000000006, 2, 3], "queries": [[0, 1], [1, 2]]}, "expected": [4, 2]}])),
    1715: ("1715_count_apples_and_oranges", "Sum fruit from every box and from the chests those boxes contain.", sql_cases()),
    1716: ("1716_calculate_money_in_leetcode_bank", "Use complete weeks plus the arithmetic tail of the partial week.", standard("totalMoney", ["n"], [{"args": {"n": 4}, "expected": 10}, {"args": {"n": 10}, "expected": 37}, {"args": {"n": 20}, "expected": 96}])),
    1717: ("1717_maximum_score_from_removing_substrings", "Remove the higher-value pair first with a stack, then remove the other pair.", standard("maximumGain", ["s", "x", "y"], [{"args": {"s": "cdbcbbaaabab", "x": 4, "y": 5}, "expected": 19}, {"args": {"s": "aabbaaxybbaabb", "x": 5, "y": 4}, "expected": 20}])),
    1718: ("1718_construct_the_lexicographically_largest_valid_sequence", "Backtrack from left to right and try larger numbers first for deterministic lexicographic maximum.", standard("constructDistancedSequence", ["n"], [{"args": {"n": 3}, "expected": [3, 1, 2, 3, 2]}, {"args": {"n": 5}, "expected": [5, 3, 1, 4, 3, 5, 2, 4, 2]}])),
    1719: ("1719_number_of_ways_to_reconstruct_a_tree", "Validate each node's minimal possible parent and detect equal-degree ambiguity.", standard("checkWays", ["pairs"], [{"args": {"pairs": [[1, 2], [2, 3]]}, "expected": 1}, {"args": {"pairs": [[1, 2], [2, 3], [1, 3]]}, "expected": 2}, {"args": {"pairs": [[1, 2], [2, 3], [2, 4], [1, 5]]}, "expected": 0}])),
    1720: ("1720_decode_xored_array", "Recover every next value by XORing the previous decoded value with encoded.", standard("decode", ["encoded", "first"], [{"args": {"encoded": [1, 2, 3], "first": 1}, "expected": [1, 0, 2, 1]}, {"args": {"encoded": [6, 2, 7, 3], "first": 4}, "expected": [4, 2, 0, 7, 4]}])),
    1721: ("1721_swapping_nodes_in_a_linked_list", "Find the kth node from the start and end, then swap their values.", standard("swapNodes", ["head", "k"], [{"args": {"head": [1, 2, 3, 4, 5], "k": 2}, "expected": [1, 4, 3, 2, 5]}, {"args": {"head": [7, 9, 6, 6, 7, 8, 3, 0, 9, 5], "k": 5}, "expected": [7, 9, 6, 6, 8, 7, 3, 0, 9, 5]}], {"head": "listnode", "return": "listnode"})),
    1722: ("1722_minimize_hamming_distance_after_swap_operations", "Union swappable indexes and match values by component counters.", standard("minimumHammingDistance", ["source", "target", "allowedSwaps"], [{"args": {"source": [1, 2, 3, 4], "target": [2, 1, 4, 5], "allowedSwaps": [[0, 1], [2, 3]]}, "expected": 1}, {"args": {"source": [5, 1, 2, 4, 3], "target": [1, 5, 4, 2, 3], "allowedSwaps": [[0, 4], [4, 2], [1, 3], [1, 4]]}, "expected": 0}])),
    1723: ("1723_find_minimum_time_to_finish_all_jobs", "Backtrack largest jobs first while pruning symmetric worker loads.", standard("minimumTimeRequired", ["jobs", "k"], [{"args": {"jobs": [3, 2, 3], "k": 3}, "expected": 3}, {"args": {"jobs": [1, 2, 4, 7, 8], "k": 2}, "expected": 11}])),
    1724: ("1724_checking_existence_of_edge_length_limited_paths_ii", "Build persistent DSU snapshots after each edge weight and query the version before the limit.", {"config": {"class": "DistanceLimitedPathsExist", "description": "Generated by scripts/_batch_1701_1750.py.", "kind": "design", "runnable": True}, "cases": {"cases": [{"kind": "design", "operations": ["DistanceLimitedPathsExist", "query", "query", "query", "query"], "arguments": [[6, [[0, 2, 4], [0, 3, 2], [1, 2, 3], [2, 3, 1], [4, 5, 5]]], [2, 3, 2], [1, 3, 3], [2, 0, 3], [0, 5, 6]], "expected": [None, True, False, True, False]}]}}),
    1725: ("1725_number_of_rectangles_that_can_form_the_largest_square", "Count rectangles whose shorter side equals the best possible square side.", standard("countGoodRectangles", ["rectangles"], [{"args": {"rectangles": [[5, 8], [3, 9], [5, 12], [16, 5]]}, "expected": 3}, {"args": {"rectangles": [[2, 3], [3, 7], [4, 3], [3, 7]]}, "expected": 3}])),
    1726: ("1726_tuple_with_same_product", "Each pair of equal products contributes eight ordered tuples.", standard("tupleSameProduct", ["nums"], [{"args": {"nums": [2, 3, 4, 6]}, "expected": 8}, {"args": {"nums": [1, 2, 4, 5, 10]}, "expected": 16}])),
    1727: ("1727_largest_submatrix_with_rearrangements", "Accumulate column heights and sort each row's heights to choose a rearranged width.", standard("largestSubmatrix", ["matrix"], [{"args": {"matrix": [[0, 0, 1], [1, 1, 1], [1, 0, 1]]}, "expected": 4}, {"args": {"matrix": [[1, 0, 1, 0, 1]]}, "expected": 3}])),
    1728: ("1728_cat_and_mouse_ii", "Memoize the finite game tree; mouse moves need one winning branch while cat moves must all preserve mouse victory.", standard("canMouseWin", ["grid", "catJump", "mouseJump"], [{"args": {"grid": ["####F", "#C...", "M...."], "catJump": 1, "mouseJump": 2}, "expected": True}, {"args": {"grid": ["M.C...F"], "catJump": 1, "mouseJump": 4}, "expected": True}, {"args": {"grid": ["M.C...F"], "catJump": 1, "mouseJump": 3}, "expected": False}])),
    1729: ("1729_find_followers_count", "Group followers per user and order by user id.", sql_cases()),
    1730: ("1730_shortest_path_to_get_food", "Breadth-first search from the start to the nearest food cell.", standard("getFood", ["grid"], [{"args": {"grid": [["X", "X", "X", "X", "X", "X"], ["X", "*", "O", "O", "O", "X"], ["X", "O", "O", "#", "O", "X"], ["X", "X", "X", "X", "X", "X"]]}, "expected": 3}, {"args": {"grid": [["X", "X", "X"], ["X", "*", "X"], ["X", "#", "X"]]}, "expected": 1}])),
    1731: ("1731_the_number_of_employees_which_report_to_each_employee", "Self-join reports to managers and aggregate count plus rounded average age.", sql_cases()),
    1732: ("1732_find_the_highest_altitude", "Track the running altitude and its maximum.", standard("largestAltitude", ["gain"], [{"args": {"gain": [-5, 1, 5, 0, -7]}, "expected": 1}, {"args": {"gain": [-4, -3, -2, -1, 4, 3, 2]}, "expected": 0}])),
    1733: ("1733_minimum_number_of_people_to_teach", "Only users in failed friendships matter; try teaching each language to that set.", standard("minimumTeachings", ["n", "languages", "friendships"], [{"args": {"n": 2, "languages": [[1], [2], [1, 2]], "friendships": [[1, 2], [1, 3], [2, 3]]}, "expected": 1}, {"args": {"n": 3, "languages": [[2], [1, 3], [1, 2], [3]], "friendships": [[1, 4], [1, 2], [3, 4], [2, 3]]}, "expected": 2}])),
    1734: ("1734_decode_xored_permutation", "XOR all numbers and odd encoded positions to recover the first value.", standard("decode", ["encoded"], [{"args": {"encoded": [3, 1]}, "expected": [1, 2, 3]}, {"args": {"encoded": [6, 5, 4, 6]}, "expected": [2, 4, 1, 5, 3]}])),
    1735: ("1735_count_ways_to_make_array_with_product", "Factor k and distribute each prime exponent among n positions with combinations.", standard("waysToFillArray", ["queries"], [{"args": {"queries": [[2, 6], [5, 1], [73, 660]]}, "expected": [4, 1, 50734910]}, {"args": {"queries": [[1, 1], [2, 2], [3, 9]]}, "expected": [1, 2, 6]}])),
    1736: ("1736_latest_time_by_replacing_hidden_digits", "Fill each unknown digit greedily while respecting a valid 24-hour time.", standard("maximumTime", ["time"], [{"args": {"time": "2?:?0"}, "expected": "23:50"}, {"args": {"time": "0?:3?"}, "expected": "09:39"}, {"args": {"time": "1?:22"}, "expected": "19:22"}])),
    1737: ("1737_change_minimum_characters_to_satisfy_one_of_three_conditions", "Try equal-letter condition and every alphabet split for the two ordering conditions.", standard("minCharacters", ["a", "b"], [{"args": {"a": "aba", "b": "caa"}, "expected": 2}, {"args": {"a": "dabadd", "b": "cda"}, "expected": 3}])),
    1738: ("1738_find_kth_largest_xor_coordinate_value", "Compute 2D prefix XOR values and select the kth largest.", standard("kthLargestValue", ["matrix", "k"], [{"args": {"matrix": [[5, 2], [1, 6]], "k": 1}, "expected": 7}, {"args": {"matrix": [[5, 2], [1, 6]], "k": 2}, "expected": 5}, {"args": {"matrix": [[5, 2], [1, 6]], "k": 4}, "expected": 0}])),
    1739: ("1739_building_boxes", "Place full triangular layers, then add the smallest front-row tail covering the remainder.", standard("minimumBoxes", ["n"], [{"args": {"n": 3}, "expected": 3}, {"args": {"n": 4}, "expected": 3}, {"args": {"n": 10}, "expected": 6}])),
    1740: ("1740_find_distance_in_a_binary_tree", "Convert parent-child links into an undirected graph and BFS between the two values.", standard("findDistance", ["root", "p", "q"], [{"args": {"root": [3, 5, 1, 6, 2, 0, 8, None, None, 7, 4], "p": 5, "q": 0}, "expected": 3}, {"args": {"root": [3, 5, 1, 6, 2, 0, 8, None, None, 7, 4], "p": 5, "q": 7}, "expected": 2}, {"args": {"root": [3, 5, 1, 6, 2, 0, 8, None, None, 7, 4], "p": 5, "q": 5}, "expected": 0}], {"root": "treenode"})),
    1741: ("1741_find_total_time_spent_by_each_employee", "Group each employee's daily sessions and sum out minus in times.", sql_cases()),
    1742: ("1742_maximum_number_of_balls_in_a_box", "Count balls by digit-sum box number.", standard("countBalls", ["lowLimit", "highLimit"], [{"args": {"lowLimit": 1, "highLimit": 10}, "expected": 2}, {"args": {"lowLimit": 5, "highLimit": 15}, "expected": 2}, {"args": {"lowLimit": 19, "highLimit": 28}, "expected": 2}])),
    1743: ("1743_restore_the_array_from_adjacent_pairs", "The original array is the path between the two degree-one endpoints.", standard("restoreArray", ["adjacentPairs"], [{"args": {"adjacentPairs": [[2, 1], [3, 4], [3, 2]]}, "expected": [1, 2, 3, 4]}, {"args": {"adjacentPairs": [[4, -2], [1, 4], [-3, 1]]}, "expected": [-2, 4, 1, -3]}])),
    1744: ("1744_can_you_eat_your_favorite_candy_on_your_favorite_day", "A query is possible when its eaten-count interval intersects that candy type's prefix interval.", standard("canEat", ["candiesCount", "queries"], [{"args": {"candiesCount": [7, 4, 5, 3, 8], "queries": [[0, 2, 2], [4, 2, 4], [2, 13, 1000000000]]}, "expected": [True, False, True]}, {"args": {"candiesCount": [5, 2, 6, 4, 1], "queries": [[3, 1, 2], [4, 10, 3], [3, 10, 100], [4, 100, 30], [1, 3, 1]]}, "expected": [False, True, True, False, False]}])),
    1745: ("1745_palindrome_partitioning_iv", "Precompute palindrome intervals and try both split points.", standard("checkPartitioning", ["s"], [{"args": {"s": "abcbdd"}, "expected": True}, {"args": {"s": "bcbddxy"}, "expected": False}])),
    1746: ("1746_maximum_subarray_sum_after_one_operation", "Kadane-style states track sums before and after using the one square operation.", standard("maxSumAfterOperation", ["nums"], [{"args": {"nums": [2, -1, -4, -3]}, "expected": 17}, {"args": {"nums": [1, -1, 1, 1, -1, -1, 1]}, "expected": 4}])),
    1747: ("1747_leetflex_banned_accounts", "Find accounts with overlapping sessions from different IP addresses.", sql_cases()),
    1748: ("1748_sum_of_unique_elements", "Sum values whose frequency is one.", standard("sumOfUnique", ["nums"], [{"args": {"nums": [1, 2, 3, 2]}, "expected": 4}, {"args": {"nums": [1, 1, 1, 1, 1]}, "expected": 0}, {"args": {"nums": [1, 2, 3, 4, 5]}, "expected": 15}])),
    1749: ("1749_maximum_absolute_sum_of_any_subarray", "The best absolute subarray sum is the range of prefix sums.", standard("maxAbsoluteSum", ["nums"], [{"args": {"nums": [1, -3, 2, 3, -4]}, "expected": 5}, {"args": {"nums": [2, -5, 1, -4, 3, -2]}, "expected": 8}])),
    1750: ("1750_minimum_length_of_string_after_deleting_similar_ends", "Shrink matching equal-character runs from both ends.", standard("minimumLength", ["s"], [{"args": {"s": "ca"}, "expected": 2}, {"args": {"s": "cabaabac"}, "expected": 0}, {"args": {"s": "aabccabba"}, "expected": 3}])),
}


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    handled = []
    for number in range(1701, 1751):
        folder, explanation, payload = META[number]
        problem_dir = ROOT / folder
        if not problem_dir.is_dir():
            raise FileNotFoundError(f"Missing expected problem folder: {folder}")
        (problem_dir / "solution.py").write_text(SOLUTIONS[number], encoding="utf-8")
        (problem_dir / "EXPLANATION.md").write_text(
            f"# {number}\n\n{explanation}\n\nTime and space are chosen to fit the official constraints.\n",
            encoding="utf-8",
        )
        tests_dir = problem_dir / "tests"
        tests_dir.mkdir(exist_ok=True)
        write_json(tests_dir / "config.json", payload["config"])
        write_json(tests_dir / "cases.json", payload["cases"])
        handled.append(folder)
    print(f"Generated {len(handled)} problems:")
    for folder in handled:
        print(f"- {folder}")


if __name__ == "__main__":
    main()
